[project]
name = "boilerplate-python"
version = "0.1.0"
description = "Boilerplate repository for Python projects."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
test = [
    "pytest"
]
lint = [
    "ruff"
]

[tool.ruff]
line-length = 100
fix = true

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["B", "D", "E", "F", "I", "N", "SIM", "UP", "C4", "S", "ARG", "PL"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107", "B027"]

[tool.ruff.lint.pydocstyle]
convention = "google"
